from dotenv import load_dotenv
from langgraph.graph import StateGraph, START, END
from typing import TypedDict
import os

load_dotenv()

#-------1.Define the state----------------------

class RAGState(TypedDict):
    question: str        #original question - set to start
    context: list[str]   #retrieved document chunks
    answer: str          #answer generated by the LLM
    step_log: list[str]  #tracks which nodes ran - for debugging

#-------2.Define nodes----------------------

def input_node(state: RAGState) -> dict:
    """Entry node — validates and logs the incoming question."""
    question = state["question"]
    log = state.get("step_log", [])
    print(f"[input_node] Question received: '{question}'")
    return {
        "step_log": log + [f"input_node: received '{question}'"]
    }


def retrieve_node(state: RAGState) -> dict:
    """
    Retrieval node — simulates fetching relevant documents.
    In production replace with:
        docs = retriever.invoke(state["question"])
        return {"context": [d.page_content for d in docs]}
    """
    question = state["question"]
    log      = state.get("step_log", [])

    # Simulated retrieval — replace with real retriever in projects
    simulated_docs = [
        f"RAG combines retrieval with generation to answer: {question}",
        "Vector databases store embeddings for fast semantic search.",
        "LangGraph enables stateful agent workflows with cycles.",
    ]
    print(f"[retrieve_node] Retrieved {len(simulated_docs)} documents")
    return {
        "context":  simulated_docs,
        "step_log": log + [f"retrieve_node: fetched {len(simulated_docs)} docs"]
    }

def generate_node(state: RAGState) -> dict:
    """
    Generation node — simulates LLM answer generation.
    In production replace with:
        chain = prompt | llm
        answer = chain.invoke({"question": ..., "context": ...})
        return {"answer": answer}
    """
    question = state["question"]
    context  = state["context"]
    log      = state.get("step_log", [])

    # Simulated generation — replace with real LLM call in projects
    context_text = "\n".join(context[:2])
    answer = f"Based on context: {context_text[:100]}... Answer to '{question}': This is a simulated answer."

    print(f"[generate_node] Answer generated: {answer[:80]}...")
    return {
        "answer":   answer,
        "step_log": log + ["generate_node: answer generated"]
    }

def output_node(state: RAGState) -> dict:
    """Final node — formats and returns the answer."""
    log = state.get("step_log", [])
    print(f"[output_node] Final answer ready")
    return {
        "step_log": log + ["output_node: complete"]
    }

# ── Step 3: Build the graph ────────────────────────────────────────────────────
def build_basic_rag_graph():
    # Create graph with the state schema
    graph = StateGraph(RAGState)

    # Add nodes — name them clearly, they appear in debug output
    graph.add_node("input",    input_node)
    graph.add_node("retrieve", retrieve_node)
    graph.add_node("generate", generate_node)
    graph.add_node("output",   output_node)

    # Add edges — define the execution flow
    graph.add_edge(START,      "input")     # entry point
    graph.add_edge("input",    "retrieve")
    graph.add_edge("retrieve", "generate")
    graph.add_edge("generate", "output")
    graph.add_edge("output",   END)         # exit point

    # Compile — converts graph definition into a runnable app
    return graph.compile()

# ── Step 4: Run the graph ──────────────────────────────────────────────────────
if __name__ == "__main__":
    app = build_basic_rag_graph()

    # Initial state — only set the fields you know at start
    initial_state = {
        "question":  "What is LangGraph and how does it work?",
        "context":   [],
        "answer":    "",
        "step_log":  [],
    }

    print("=" * 60)
    print("Running basic LangGraph RAG pipeline")
    print("=" * 60)

    # invoke() runs the graph synchronously
    final_state = app.invoke(initial_state)

    print("\n" + "=" * 60)
    print("Final State")
    print("=" * 60)
    print(f"Question  : {final_state['question']}")
    print(f"Context   : {len(final_state['context'])} chunks retrieved")
    print(f"Answer    : {final_state['answer'][:100]}...")
    print(f"Step log  :")
    for step in final_state["step_log"]:
        print(f"  → {step}")

    # stream() yields state after each node — great for debugging
    print("\n" + "=" * 60)
    print("Streaming mode — see state after each node")
    print("=" * 60)
    for step_output in app.stream(initial_state):
        node_name = list(step_output.keys())[0]
        print(f"\nAfter node: '{node_name}'")
        state_update = step_output[node_name]
        for key, val in state_update.items():
            if isinstance(val, list):
                print(f"  {key}: {len(val)} items")
            else:
                print(f"  {key}: {str(val)[:60]}")